---
- name: install epel
  yum: name=epel-release

- name: Install glusterfs packages for mount and unmount
  yum: name=glusterfs-client,glusterfs-rdma,glusterfs-fuse

- name: Gluster-3.10 repo
  yum_repository:
    name: centos-gluster-3.10
    description: CentOS Storage SIG repo for gluster 3.10
    baseurl: http://mirror.centos.org/centos/$releasever/storage/$basearch/gluster-3.10/
    gpgkey: https://raw.githubusercontent.com/CentOS-Storage-SIG/centos-release-storage-common/master/RPM-GPG-KEY-CentOS-SIG-Storage
    enabled: yes

- name: Install glusterfs-server
  yum:
    name: glusterfs-server
